# Write a program to input eight numbers from the user and display all the unique
# numbers (once).
s1= set()
n = input("enter number 1  ")
s1.add(int(n))
n = input("enter number 2  ")
s1.add(int(n))
n = input("enter number 3  ")
s1.add(int(n))
n = input("enter number 4  ")
s1.add(int(n))
n = input("enter number 5  ")
s1.add(int(n))
n = input("enter number 6  ")
s1.add(int(n))
n = input("enter number 7  ")
s1.add(int(n))
n = input("enter number 8  ")
s1.add(int(n))
print(s1)